spring:
  datasource:
    url: jdbc:mysql://x.withyan.cn:3306/time_manager?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jmx:
    enabled: false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

  redis:
    host: x.withyan.cn
    port: 6379
    password: Your password

PASSWORD_MIN_LENGTH: 6

TOKEN_TIMEOUT_MS: 30