spring:
  datasource:
    url: jdbc:mysql://smileyan.cn:3306/login_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Yan1996>
    driver-class-name: com.mysql.cj.jdbc.Driver
  jmx:
    enabled: false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

  redis:
    host: withyan.cn
    port: 6379
    password: 123456

PASSWORD_MIN_LENGTH: 6

TOKEN_TIMEOUT_MS: 30